@startuml

class Capacete {
    nome: String
    cor: String
    tamanho: Interger
    preco: Double

}

class Marca {
    nome: String
    modelo: String
}

enum Categoria {
    fechado: int
    aberto: int
    articulado: int
    
}


class Viseira {
    marca: String
    cor: String
    tipo: String
    
}

enum Jugular {
    engateRapido: int
    duploD: int
}



class Lote{
    codigo: String 
    quantidade: Integer
    dataFabricacao: LocalDate
}

abstract class Pessoa {
    nome: String
}

class PessoaFisica{
    cpf: String
    dataNascimento: Date
}

class PessoaJuridica{
    cnpj: String
}

class Usuario {
    username: String
    senha: String
    email: String
    dataCadastro: LocalDate
    perfil: Perfil
}


class Funcionario{
    salario: BigDecimal
    dataContratacao: LocalDate
    cargo: String
}


class Telefone {
    codigoArea: String
    numero: String
}

class Endereco {
    logradouro: String
    bairro: String
    numero: String
    complemento: String
    cep: String
}


class Cidade {
    nome: String
}

class Estado {
    nome: String
    sigla: String
}

class Pedido {
    data: LocalDateTime
    valorTotal: Double
    enderecoEntrega: Endereco
}

class ItemPedido {
    quantidade: Integer
    preco: Double
}

class StatusPedido {
    dataAtualizacao: LocalDateTime
}

enum SituacaoPedido {
    aguardandoPagamento: int
    pagamentoConfirmado: int
    cancelado: int
    enviado: int
    entregue: int
    devolvido: int
}


abstract class Pagamento {
    valor: Double
    dataPagamento: LocalDateTime
    dataVencimento: LocalDateTime
    tipoPagamento: TipoPagamento
}

enum TipoPagamento{
    pix: int
    boleto : int
    cartao : int
}


class Pix {
    chave: String
}

class Boleto {
    codigoBarras: String
}

class Cartao {
    nomeTitular: String
    numero: String
    codigoSeguranca: String
    validade: LocalDate
}

class CartaoPagamento {
    tipoCartao: TipoCartao
}

enum Perfil {
    funcionario: int
    administrador: int
}

enum TipoCartaoPagamento {
    debito: int
    credito: int
}

'relacionamento'


Capacete "*" --> "1" Marca
Capacete "*" --> "1" Categoria
Capacete "*" --> "1" Jugular
Capacete "*" --> "1" Viseira

ItemPedido "*" --> "1" Capacete
Lote "1" --> "*" Capacete

Pedido "*" --> "1" Usuario
Pedido "1" --> "*" ItemPedido
Pedido "1" --> "*" StatusPedido
Pedido "1" --> "1" Pagamento
StatusPedido "*" --> "1" SituacaoPedido

CartaoPagamento "*" --> "1" Cartao

Pagamento "*" --> "1" TipoPagamento
CartaoPagamento "*" --> "1" TipoCartaoPagamento
Pix --|> Pagamento
Boleto --|> Pagamento
CartaoPagamento --|> Pagamento
Usuario "1"--> "*" Cartao :lista cartoes

Usuario "1" <|-- "1" Pessoa

Pessoa "1" --> "*" Telefone
Pessoa "*" --> "*" Endereco
PessoaFisica --|> Pessoa
PessoaJuridica --|> Pessoa

Usuario "*" --> "1" Funcionario
Usuario "*" --> "*" Capacete : listaDesejos
Usuario "1" --> "1" Perfil
Cidade "*" --> "1" Estado
Endereco "*" --> "1" Cidade
Pedido "*" --> "1" Endereco

@enduml